final_project.ipynb: final_version.ipynb table.tex heatmap.png
	pdflatex report
	pdflatex report
	pdflatex report

table.tex: cases.csv ctrls.csv
	python prepare_results.py


.PHONY: all clean

all: final_project.ipynb

clean:
	rm -f final_project.ipynb